version: '2'

services:
  server1:
    image: nginx
    volumes:
      - ./server1:/usr/share/nginx/html 
    ports:
        - 7000:80
  server2:
    image: nginx
    volumes:
      - ./server2:/usr/share/nginx/html 
    ports:
        - 7001:80
  reverse-proxy:
    image: nginx
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80